### PR TITLE
Drop GraphQl support

### PR DESCRIPTION
**Pull request by danielSanchezQ**
* Removed graphql endpoints, schemas and impls
* Removed graphql related tests

### CODE REVIEW

**Review by eugene-babichenko — COMMENTED** [review]
Also please remove GraphQL deps from `Cargo.toml`.

**Comment by eugene-babichenko** [comment]
On top of that there is a whole load of test data under `vit-servicing-station-tests/resources/graphql_requests/templates`.

**Comment by eugene-babichenko** [comment]
We still have something

```
❯ rg graphql
README.md
86:The VIT servicing station offers a **GraphQL** playground endpoint (`api/v0/graphql/playground`) designed to offer a user friendly approach to the API.

vit-servicing-station-tests/askama.toml
3:dirs = ["resources/graphql_requests/templates"]
6:path = "::graphql_escape::graphql"
7:extensions = ["graphql"]

vit-servicing-station-tests/src/tests/non_functional/mod.rs
4:use crate::common::clients::graphql::GraphqlClient;
18:    graphql_client: GraphqlClient,
63:        mut graphql_client: GraphqlClient,
66:        graphql_client.disable_log();
71:            graphql_client,
80:        self.graphql_client
95:                .graphql_client
102:                .graphql_client
121:                .graphql_client
136:    let graphql_client = server.graphql_client();
138:    let request = VitRestRequestGenerator::new(snapshot, rest_client, graphql_client);
156:    let graphql_client = server.graphql_client();
158:    let request = VitRestRequestGenerator::new(snapshot, rest_client, graphql_client);

vit-servicing-station-tests/src/common/clients/rest.rs
202:    pub fn graphql(&self, data: String) -> Result<serde_json::Value, RestError> {
203:        self.post(&self.path_builder.graphql(), data)
256:    pub fn graphql(&self) -> String {
257:        self.path("graphql")
```

**Comment by eugene-babichenko** [comment]
Also there is something called `askama` that might need to be removed. cc @dkijania

**Comment by danielSanchezQ** [comment]
Pending the `askama` confirmation from @dkijania

**Comment by dkijania** [comment]
Just kill It all :)

**Review by eugene-babichenko — CHANGES_REQUESTED** [review]
```
❯ rg graphql
vit-servicing-station-tests/src/tests/non_functional/mod.rs
17:    graphql_client: GraphqlClient,
62:        mut graphql_client: GraphqlClient,
65:        graphql_client.disable_log();
70:            graphql_client,
79:        self.graphql_client
94:                .graphql_client
101:                .graphql_client
120:                .graphql_client
135:    let graphql_client = server.graphql_client();
137:    let request = VitRestRequestGenerator::new(snapshot, rest_client, graphql_client);
155:    let graphql_client = server.graphql_client();
157:    let request = VitRestRequestGenerator::new(snapshot, rest_client, graphql_client);
```

**Comment by danielSanchezQ** [comment]
I really need to run something like that. 🤦

**Review by eugene-babichenko — APPROVED** [review]

**Pull request merged**
