### PR TITLE
Vit station cli

### PR DESCRIPTION
**Pull request by danielSanchezQ**
Implemented a tiny tool (that probably may grow in the future) to interact with the vit-servicing-station ecosystem.

### CODE REVIEW

**Comment by danielSanchezQ** [comment]
CI/CD not working. Ill close and reopen to see if they are launched again.

**Comment by dkijania** [comment]
when running command:

`cargo run -- api-token add --db-url ..\test\vit_station_new.db`

it freezes without and outcome

**Comment by danielSanchezQ** [comment]
Gonna check that, thanks!

**Comment by dkijania** [comment]
Did we have some schema change in token table?
In above row we have old token below new one
image

There are some minor panics in cli:
> `cargo run -- api-token add --db-url ..\resources\tests\vit_station_newdd.db --tokens BLfYL9TnB8Lqgg,BLfYL9TnB8Lqgg`

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidLength', vit-servicing-station-cli\src\app.rs:76:25`

> ` cargo run -- api-token add --db-url ..\resources\tests\vit_station_newdd.db --tokens BLfYL9TnB8Lqgg BLfYL9TnB8Lqgg`

`Error: no such table: api_tokens  // i thin it should complain that db does not exists`

> `cargo run -- api-token add --db-url ..\resources\tests\vit_station_new.db --tokens BLfYL9TnB8Lqgg BLfYL9TnB8Lqgg`

`Error: UNIQUE constraint failed: api_tokens.token`

**Comment by danielSanchezQ** [comment]
> Did we have some schema change in token table?
> In above row we have old token below new one
> image
> 

We always planned the dates to be timestamps. The thing is that SQLLite is quite "flexible" and it is just transforming those date looking information to a `i64`. It did not matter since it was just earlier testing. They **should** be timestamps though.

I'll take a look at those other errors. Thanks!

**Comment by dkijania** [comment]
is it ready to recheck?

**Comment by danielSanchezQ** [comment]
@dkijania It should, thanks!.

**Comment by dkijania** [comment]
Below small issues are still visible:
```
thread 'main' panicked at 'called Result::unwrap()on anErr value: InvalidLength', vit-servicing-station-cli\src\app.rs:76:25

cargo run -- api-token add --db-url ..\resources\tests\vit_station_newdd.db --tokens BLfYL9TnB8Lqgg BLfYL9TnB8Lqgg

Error: no such table: api_tokens // i thin it should complain that db does not exists

cargo run -- api-token add --db-url ..\resources\tests\vit_station_new.db --tokens BLfYL9TnB8Lqgg BLfYL9TnB8Lqgg

Error: UNIQUE constraint failed: api_tokens.token
```

But i can report them as issues not to block this pr

**Comment by danielSanchezQ** [comment]
Yeah, lets do that @dkijania . I'm not sure what to do with that exactly now. Thanks!!

**Pull request merged**
