### PR TITLE
Gracefully exit and error reporting on application startup

### LINKED ISSUE #27: Panic when no --block0-path provided
If i run command like below:

```
cargo run -- --db-url test\vit_station_new.db
```
Then got a panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\v0\context.rs:32:5
```

While it should provide some nicely formatted message about lack of --block-path argument

### LINKED ISSUE #33: Better error reporting when Cors schema is invalid
config file:
```
{
  "cors": {
    "max_age_secs": 30,
    "allowed_origins": [
      "localhost:3030"
    ]
  },
  "address": "127.0.0.1:3030",
  "tls": {
	"cert_file": "a",
    "priv_key_file": "b"
  },
  "db_url": "test/vit_station_new.db",
  "block0_path": "test/block0.bin"
}
```

command:
`cargo run -- --db-url test\vit_station_new.db --block0-path test\block0.bin  --in-settings-file config.json`

output:
`thread 'main' panicked at 'missing scheme', C:\Users\Dariusz\.cargo\registry\src\github.com-1ecc6299db9ec823\warp-0.2.2\src\filters\cors.rs:614:24`

### PR DESCRIPTION
**Pull request by danielSanchezQ**
Fix #27
Fix #33

### CODE REVIEW

**Comment by dkijania** [comment]
issue #33 is still failing. #27 is fixed

**Comment by danielSanchezQ** [comment]
I'll recheck #33. Thanks

**Comment by danielSanchezQ** [comment]
Indeed it was wrong. It should be ok now @dkijania!

**Comment by dkijania** [comment]
working good!

**Pull request merged**
